language: objective-c
osx_image: xcode6.4
xcode_workspace: mpx.xcworkspace
xcode_scheme: mpx
before_install:
- brew update || brew update
- brew upgrade
install:
- $TRAVIS_BUILD_DIR/install_deps.sh
- pod install --project-directory=$TRAVIS_BUILD_DIR
