language: objective-c
osx_image: xcode7
xcode_workspace: mpx.xcworkspace
xcode_scheme: mpx
before_install:
- brew update || brew update
- brew outdated xctool || brew upgrade xctool
install:
- travis_wait $TRAVIS_BUILD_DIR/install_deps.sh
- pod install --project-directory=$TRAVIS_BUILD_DIR
