language: objective-c
osx_image: xcode6.4
xcode_workspace: mpx.xcworkspace
xcode_scheme: mpx
before_install:
- brew update || brew update
- brew upgrade
install:
- $TRAVIS_BUILD_DIR/phill84/mpx/install_deps.sh
